### ISSUE TITLE
Code samples showing in front of the terminal in Getting started with apko.

### ISSUE THREAD

**Issue by debasishbsws** [chainguard-dev/edu#1024]
**Describe the bug**
![image](https://github.com/chainguard-dev/edu/assets/65381620/15fcf406-0aed-4507-9ab6-a50d0aea1863)

The code samples are popping in front of the terminal. Also the side NAV

**To Reproduce**
Steps to see this behavior:
1. Go to 'https://edu.chainguard.dev/open-source/apko/getting-started-with-apko/'
2. Scroll down to '3. Test the image with Docker'

**Expected behavior**
All the code samples should not be in front of the terminal.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, edge, Brave]

**Comment by jamonation** [comment]
I tested with an updated Brave and Edge on Windows 10 and can't seem to reproduce this:
![brave](https://github.com/chainguard-dev/edu/assets/328553/b84f401c-bce5-4e8b-9b37-84491d005ef9)
![edge](https://github.com/chainguard-dev/edu/assets/328553/e16082f4-1beb-4fd5-81d9-d0d7649ce6a8)

I suspect there have been some CSS changes since you reported it @debasishbsws - if it is still an issue feel free to reopen this!

**Comment by debasishbsws** [comment]
It works fine now.

**Comment by BHAVISHYA2005** [comment]
LGTM 🖒
