### ISSUE TITLE
Fix the installation instruction link on Getting Started With Chainguard Images (topic: Verifying a Signature with Cosign)

### ISSUE THREAD

**Issue by lucasjct** [chainguard-dev/edu#1985]
**Describe the bug**
Hi, good morning! 

There is a link directed to 404 page on **Getting Started With Chainguard Images** (topic: Verifying a Signature with Cosign)

**To Reproduce**
1. Go to 'https://courses.chainguard.dev/path/linkys-guide-to-chainguard-images/getting-started-with-chainguard-images'
2. Click on '__How to Verify Images__'
3. Scroll down to 'Verifying a Signature with Cosign' and click on __installation instruction__ .

**Expected behavior**
Open the correct link when the user click on _installation instruction_.
I could imagine that the correct link would be: https://docs.sigstore.dev/cosign/system_config/installation/

**Screenshots**

![Image](https://github.com/user-attachments/assets/cd579fe2-e30e-4459-82e3-19dfeb7397ab)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucasjct** [comment]
I have checked others link in the same page and we have the same issue. For example:

https://token.actions.githubusercontent.com/
https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main

Anyway, chainguard has great and very rich documentation. Congrats!

**Comment by smythp** [comment]
Hi Lucas, thanks for documenting the broken link. I've updated the page with the correct install link.

For the second identification link, that is the correct URL. Using the link interactively will result in a 404, since some additional headers are probably required that get used by tooling such as Cosign. (It may be something else like request type but headers seems likely.) I've added a note to the lesson so that this behavior doesn't surprise anyone else.

Happy New Year! Thank you for the contribution!.
