### ISSUE TITLE
Switch cosign docs to show cosign attest from cosign attach

### ISSUE THREAD

**Issue by eddiezane** [chainguard-dev/edu#378]
Our docs currently show that attaching an sbom to an image should be done with `cosign attach` and then signed with `cosign sign`.

We apparently want to move to using `cosign attest`

https://edu.chainguard.dev/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign/#attach-the-sbom-to-the-image

cc @mattmoor

**Comment by mattmoor** [comment]
Yeah, signing the `.sbom` doesn't do anything useful.  What we want is an attestation, which would look something like:

SPDX:
```shell
cosign attest --type https://spdx.dev/Document --predicate spdx.json <IMAGE>
```

CycloneDX:
```shell
cosign attest --type https://cyclonedx.org/bom --predicate cdx.json <IMAGE>
```

I'm going from memory, so I may have missed something, but I believe these are right.

One of the key subtleties here is the use of the URI form of `--type`, which we should advocate for because of two reasons:
1. This avoids the `CosignPredicate` envelope, which `cosign` 1.x injects when using `--type spdx|cyclonedx`, and
2. This avoids any confusion around what the actual `predicateType` is when authoring policies.

We should switch all our usage of shortnames to URIs as well ([see also](https://github.com/chainguard-dev/policy-catalog/pull/101))

**Comment by mattmoor** [comment]
cc @jamonation

**Comment by ltagliaferri** [comment]
We have two open issues about Cosign signing SBOMS (https://github.com/chainguard-dev/edu/issues/371 and https://github.com/chainguard-dev/mono/issues/7663), we have notes in that second issue regarding SBOMs and Enforce.

**Comment by ltagliaferri** [comment]
https://github.com/chainguard-dev/edu/pull/476
