### ISSUE TITLE
Document how to pre-select the auth provider in chainctl auth login

### ISSUE THREAD

**Issue by kimsterv** [chainguard-dev/edu#767]
To set default social login add
`default:
  social-login: google # (or github or gitlab)`

To set default identity provider set
`default:
  identity-provider: <idp ID>`

use chainctl config edit to do this but I think chainctl config set default.social-login might work too?

Also a related comment on chainctl docs (might be worth splitting out a new issue for this) -
"I don't see anything (for schema or docs on the config). I gotta be honest I do find the docs a little hard to navigate. There are auto generated docs for all the commands but we don't have an overview page for chainctl that I can find"

**Comment by SharpRake** [comment]
I opened a PR that will add these details: https://github.com/chainguard-dev/edu/pull/776

I also take the point about the chainctl docs. I think we're due to take another look at how we're organizing that information. I also have some vague ideas for a `chainctl` onboarding-type doc. Anyway, I started a new issue to track this work: https://github.com/chainguard-dev/edu/issues/777
