### ISSUE TITLE
Surface created and last updated dates on pages

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#821]
We record this information but it's not surfaced. This can likely be toggled on through the theme, or we can pull in the logic from the blog part of the theme

**Comment by erikaheidi** [comment]
This is related to #1008 . Once that is done it will be easier to implement also for the non-automated pages, with the caveat that these will require manual updates to the createdAt and updatedAt fields.

**Comment by erikaheidi** [comment]
I started with this one because the autodocs update will require a few tricks to detect when the content actually changed to only then update the lastMod parameter.

I opened a PR to add the last modified date  and time to the bottom of pages: https://github.com/chainguard-dev/edu/pull/1147

I wasn't sure if we needed to show the created date as well. I can add it if needed.

**Comment by erikaheidi** [comment]
PR is merged, so I'm closing this one now.
